export const ActionTypes = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_ITEM: 'REMOVE_ITEM',
    INCREASE: 'INCREASE',
    DECREASE: 'DECREASE',
    CHECKOUT: 'CHECKOUT',
    CLEAR: 'CLEAR',
    
    // sorting action types
    SORT_BY_TITLE: 'SORT_BY_TITLE',
    ASCEND: 'ASCEND',
    DESCEND: 'DESCEND',
    SORT_BY_SLICE: 'SORT_BY_SLICE',
    RETURN_TO_DEFAULT: 'RETURN_TO_DEFAULT'
}



